version: '3.4'

services:
  docker22test:
    image: ${DOCKER_REGISTRY-}docker22test
    build:
      context: .
      dockerfile: Docker22Test/Dockerfile

  consoleapp2:
    image: ${DOCKER_REGISTRY-}consoleapp2
    build:
      context: .
      dockerfile: ConsoleApp2/Dockerfile

